Add docker building

diff --git a/Project/Dockerfile b/Project/Dockerfile
--- a/Project/Dockerfile
+++ b/Project/Dockerfile
@@ -1,5 +1,56 @@
-FROM eclipse-temurin:21-jre
-RUN mkdir /opt/app
-COPY docker_files/ /opt/app/
-CMD ["/opt/app/run.sh"]
+##### DEPENDENCIES
+
+FROM --platform=linux/amd64 node:20-alpine AS deps
+RUN apk add --no-cache libc6-compat openssl1.1-compat
+WORKDIR /app
+
+# Install dependencies based on the preferred package manager
+
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml\* ./
+
+RUN \
+    if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+    elif [ -f package-lock.json ]; then npm ci; \
+    elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i; \
+    else echo "Lockfile not found." && exit 1; \
+    fi
+
+##### BUILDER
+
+FROM --platform=linux/amd64 node:20-alpine AS builder
+ARG DATABASE_URL
+ARG NEXT_PUBLIC_CLIENTVAR
+WORKDIR /app
+COPY --from=deps /app/node_modules ./gp-system/node_modules
+COPY ./gp-system .
+
+# ENV NEXT_TELEMETRY_DISABLED 1
+
+RUN \
+    if [ -f yarn.lock ]; then SKIP_ENV_VALIDATION=1 yarn build; \
+    elif [ -f package-lock.json ]; then SKIP_ENV_VALIDATION=1 npm run build; \
+    elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && SKIP_ENV_VALIDATION=1 pnpm run build; \
+    else echo "Lockfile not found." && exit 1; \
+    fi
+
+##### RUNNER
+
+FROM --platform=linux/amd64 gcr.io/distroless/nodejs20-debian12 AS runner
+WORKDIR /app
+
+ENV NODE_ENV production
+
+# ENV NEXT_TELEMETRY_DISABLED 1
+
+COPY --from=builder /app/next.config.js ./gp-system
+COPY --from=builder /app/public ./gp-system/public
+COPY --from=builder /app/package.json ./gp.system/package.json
+
+COPY --from=builder /app/.next/standalone ./gp-system/
+COPY --from=builder /app/.next/static ./gp-system/.next/static
+
+EXPOSE 3000
+ENV PORT 3000
+
+CMD ["server.js"]
 
